#!/bin/bash
# Simple entrypoint for the bigtruedata/cron Docker image.
# Copyright (C) 2017 BigTrueData

set -e

trap exit SIGINT
trap exit SIGTERM

# configure timezone if provided
if [ -n "$TIME_ZONE" ]; then
  cp /usr/share/zoneinfo/"$TIME_ZONE" /etc/localtime
  echo "$TIME_ZONE" > /etc/timezone
fi

# configure timeserver if not provided
if [ -z "$TIME_SERVER" ]; then
  TIME_SERVER=pool.ntp.org
fi

# configure cron (no action if not provided)
echo "$CRON_ENTRY" | crontab -

ntpd -p "$TIME_SERVER" && crond -f
